name: GitHub Actions Secrets and Variables Demo

on:
  push:
    branches:
      - main

jobs:
  demo:
    runs-on: ubuntu-latest
    env:
      # This is a config variable that will NOT be masked
      CONFIG_VARIABLE: 'This is a config variable.'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print masked secret
      run: echo "My Masked Secret: ${{ secrets.MY_MASKED_SECRET }}"

    - name: Print config variable
      run: echo "My Config Variable: ${{ env.CONFIG_VARIABLE }}"